### ISSUE TITLE
encode 时应严格检查数组

### ISSUE THREAD

**Issue by sumneko** [actboy168/json.lua#1]
考虑以下情况
```lua
local hash = 0x12345678
local data = {}
data[hash] = true

json.encode(data)
```
这里这段代码应该是一个错误，但是实际编码的时候，json库会认为 `data` 是一个数组，并且由于 `hash` 通常会非常巨大，导致尝试编码一个非常巨大的数组，耗尽了CPU资源。

在尝试编码数组时，应当确认数组的每一项都是有值的，如果用户希望编译出 `null` ，应当显性放置 `json.null` 。

**Comment by actboy168** [comment]
大多数的lua上的json库都支持稀疏数组，所以也随手支持了。不过这个功能只是增加了一些便利性，但损失了严谨性。确实不是很有必要。

不过考虑到兼容性，我把稀疏数组做成了一个开关，你可以将它关闭。
